 const category_skill={
 "ProgrammingLanguages": {
  "Python": "🐍",
  "Java": "☕",
  "C++": "🔵",
  "C#": "🎵",
  "Go": "💨",
  "Rust": "🦀",
  "Swift": "🕊️",
  "Kotlin": "📱",
  "TypeScript": "🔷"
},

  "WebDevelopment": {
  "HTML5": "📜",
  "CSS3": "🎨",
  "React": "⚛️",
  "Vue.js": "🌿",
  "Angular": "🅰️",
  "Node.js": "🌱",
  "Next.js": "⏩",
  "Svelte": "🔥",
  "Tailwind CSS": "💨",
  "Bootstrap": "🟣"
},
"BackendDevelopment": {
  "Node.js": "🌿",
  "Express": "🚀",
  "Django": "🐍",
  "Flask": "🍶",
  "Spring Boot": "🌾",
  "Ruby on Rails": "💎",
  "ASP.NET Core": "🖥",
  "FastAPI": "⚡",
  "GraphQL": "🔺",
  "gRPC": "🔗"
},
"DevOpsAndCloud": {
  "Docker": "🐳",
  "Kubernetes": "☸️",
  "Amazon AWS": "🌩",
  "Microsoft Azure": "🖥",
  "Google Cloud": "☁️",
  "Terraform": "🏗️",
  "Jenkins": "🔄",
  "CI/CD Pipelines": "🔧",
  "Bash": "🐚",
  "Linux": "🐧"
},
"DatabaseManagement": {
  "MySQL": "🐬",
  "PostgreSQL": "🐘",
  "MongoDB": "🍃",
  "Redis": "🧠",
  "Cassandra": "📦",
  "Elasticsearch": "🔍",
  "Firebase": "🔥",
  "DynamoDB": "📊",
  "Neo4j": "🔗"
},
"Cybersecurity": {
  "Ethical Hacking": "🕵️",
  "Penetration Testing": "🔑",
  "Network Security": "🛡️",
  "Cryptography": "🔏",
  "Web Application Security": "🌐",
  "Cloud Security": "🔒",
  "Incident Response": "🚨",
  "Forensic Analysis": "🔬",
  "Threat Intelligence": "🧐",
  "Zero Trust Security": "🔓"
},
"AIAndMachineLearning": {
  "Deep Learning": "🧠",
  "TensorFlow": "📊",
  "PyTorch": "🔥",
  "Computer Vision": "👁",
  "Natural Language Processing": "📖",
  "Reinforcement Learning": "🎮",
  "Big Data": "💾",
  "Data Engineering": "🛠",
  "AutoML": "🤖",
  "AI Ethics": "⚖️"
},
"BlockchainAndWeb3": {
  "Smart Contracts": "📜",
  "Ethereum": "⛓",
  "Solidity": "📝",
  "Rust": "🦀",
  "DeFi": "🏦",
  "NFT Development": "🎭",
  "Hyperledger": "🔗",
  "DApps": "🏗",
  "IPFS": "📦",
  "Layer 2 Solutions": "⚡"
},
"GraphicDesignAndVideoEditing": {
  "Adobe Photoshop": "🖌",
  "Adobe Illustrator": "✏️",
  "Figma": "📐",
  "Adobe Premiere Pro": "🎥",
  "Final Cut Pro": "🎞️",
  "DaVinci Resolve": "🎬",
  "Adobe After Effects": "🌟"
},
"Engineering": {
  "Mechanical Engineering": "⚙️",
  "Electrical Engineering": "💡",
  "Civil Engineering": "🏗",
  "Chemical Engineering": "🧪",
  "Aerospace Engineering": "✈️",
  "Biomedical Engineering": "🏥",
  "Automotive Engineering": "🚗",
  "Robotics": "🤖",
  "Structural Engineering": "🏛",
  "Materials Science": "🔬"
},
"BusinessStrategy": {
  "Market Research": "📊",
  "Competitive Analysis": "⚖️",
  "Business Development": "🚀",
  "Project Management": "📅",
  "Risk Management": "⚠️",
  "Lean Startup": "📈",
  "Agile Methodology": "🔄",
  "Scrum": "🌀",
  "Kanban": "📋",
  "Business Intelligence": "💡"
},

  "Marketing": {
    "SEO": "🔍",
    "Content Marketing": "📝",
    "Social Media Marketing": "📱",
    "Email Marketing": "📧",
    "Growth Hacking": "📈",
    "Google Ads": "📢",
    "Facebook": "📘",
    "Branding": "🏷️",
    "Affiliate Marketing": "🤝",
    "Copywriting": "✍️"
  },
  "FinanceAndAccounting": {
    "Financial Modeling": "📊",
    "Corporate Finance": "🏦",
    "Investment Banking": "💰",
    "Cryptocurrency": "₿",
    "Accounting": "🧾",
    "Taxation": "💳",
    "Auditing": "📑",
    "Risk Management": "⚠️",
    "FinTech": "📲",
    "Bookkeeping": "📚"
  },
  "Entrepreneurship": {
    "Startup Funding": "💵",
    "Venture Capital": "🏢",
    "Bootstrapping": "🛠",
    "Lean Startup": "📉",
    "E-commerce": "🛍",
    "Dropshipping": "📦",
    "Freelancing": "💻",
    "Business Law": "⚖",
    "Franchising": "🔗",
    "Small Business Management": "📊"
  },
  "GraphicDesign": {
    "Adobe Photoshop": "🎨",
    "Adobe Illustrator": "🖌",
    "Canva": "🖼",
    "Figma": "📐",
    "Sketch": "✏️",
    "Typography": "🔠",
    "Logo Design": "🏷️",
    "UX/UI Design": "🖥",
    "Infographic Design": "📊",
    "Motion Graphics": "🎞"
  },
  "3DAndGameDevelopment": {
    "Blender": "🎭",
    "Maya": "🎨",
    "Unity": "🎮",
    "Unreal Engine": "🚀",
    "Character Rigging": "🦾",
    "VR/AR": "🕶",
    "Level Design": "🏗",
    "Game Physics": "🎢",
    "Cinematics": "🎬",
    "Game AI": "🤖"
  },
  "Photography": {
    "Portrait Photography": "📸",
    "Landscape Photography": "🌄",
    "Product Photography": "📷",
    "Photo Editing": "🖼",
    "Lighting Techniques": "💡",
    "Drone Photography": "🚁",
    "Event Photography": "🎭",
    "Macro Photography": "🔬",
    "Composition": "🖼",
    "Camera Equipment": "📷"
  },
  "MedicalSciences": {
    "General Medicine": "⚕",
    "Surgery": "🔪",
    "Radiology": "🩻",
    "Pediatrics": "👶",
    "Cardiology": "❤️",
    "Neurology": "🧠",
    "Oncology": "🦠",
    "Orthopedics": "🦴",
    "Anesthesiology": "💉",
    "Endocrinology": "🧪"
  },
  "AlternativeMedicine": {
    "Ayurveda": "🌿",
    "Homeopathy": "💊",
    "Acupuncture": "🩸",
    "Traditional Chinese Medicine": "🀄",
    "Naturopathy": "🍃",
    "Herbal Medicine": "🌱",
    "Chiropractic": "💆",
    "Holistic Healing": "🧘",
    "Yoga Therapy": "🧘‍♂️",
    "Meditation Therapy": "🕉"
  },
  "HealthcareTechnology": {
    "Medical Imaging": "🖥",
    "Telemedicine": "📞",
    "Wearable Health Tech": "⌚",
    "EHR/EMR Systems": "📋",
    "Health Data Analytics": "📊",
    "AI in Healthcare": "🤖",
    "Medical Robotics": "🦾",
    "Pharmaceutical Research": "🧪",
    "Biotechnology": "🧬",
    "CRISPR": "🧫"
  },
  "SoftSkills": {
    "Communication Skills": "🗣",
    "Leadership": "👑",
    "Public Speaking": "🎤",
    "Negotiation": "🤝",
    "Time Management": "⏳",
    "Emotional Intelligence": "💡",
    "Critical Thinking": "🧠",
    "Decision Making": "⚖",
    "Conflict Resolution": "🕊",
    "Networking": "🌐"
  },
  "LanguageLearning": {
    "English": "🇬🇧",
    "Spanish": "🇪🇸",
    "French": "🇫🇷",
    "Mandarin Chinese": "🇨🇳",
    "German": "🇩🇪",
    "Japanese": "🇯🇵",
    "Russian": "🇷🇺",
    "Arabic": "🇸🇦",
    "Hindi": "🇮🇳",
    "Italian": "🇮🇹"
  },
  "ScienceAndResearch": {
    "Physics": "🔬",
    "Quantum Mechanics": "⚛",
    "Astronomy": "🌌",
    "Biochemistry": "🧪",
    "Genetics": "🧬",
    "Nanotechnology": "⚙",
    "Artificial Intelligence Research": "🤖",
    "Geology": "🌍",
    "Meteorology": "🌦",
    "Climate Science": "🌍"
  }
}
export default category_skill